import { access, readFile, readdir } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const docsDir = path.join(root, "docs");

function invariant(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

async function exists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function localReferences(html) {
  const references = [];
  const tagPattern = /<(?:a|img|link)\b[^>]*\b(?:href|src)="([^"]+)"[^>]*>/gi;
  let match;
  while ((match = tagPattern.exec(html)) !== null) {
    const value = match[1];
    if (!/^(?:https?:|mailto:|#)/i.test(value)) {
      references.push(value);
    }
  }
  return references;
}

async function verifyReference(pagePath, reference) {
  const clean = reference.split("#")[0].split("?")[0];
  if (!clean) {
    return;
  }
  let target = path.resolve(path.dirname(pagePath), clean);
  invariant(target.startsWith(docsDir), `${path.relative(root, pagePath)} escapes docs via ${reference}`);
  if (clean.endsWith("/")) {
    target = path.join(target, "index.html");
  }
  invariant(await exists(target), `${path.relative(root, pagePath)} has broken local reference ${reference}`);
}

function executeRoutingScript(html, { search = "", browserLanguage = "en-US", android = false } = {}) {
  const match = /<script>\s*([\s\S]*?)<\/script>/i.exec(html);
  invariant(match, "Generated page is missing its head routing script");
  let replacement = null;
  const window = {
    Android: android ? { onPdfReady() {} } : undefined,
    location: {
      hash: "",
      search,
      replace(value) {
        replacement = value;
      }
    },
    navigator: {
      language: browserLanguage,
      userLanguage: browserLanguage
    }
  };
  vm.runInNewContext(match[1], { decodeURIComponent, encodeURIComponent, window }, { timeout: 1000 });
  return replacement;
}

async function main() {
  const languages = JSON.parse(await readFile(path.join(docsDir, "langs.json"), "utf8"));
  const codes = Object.keys(languages);
  const expectedPdfNames = new Set(codes.map((code) => `cv${code === "en" ? "" : `_${code}`}.pdf`));
  const actualPdfNames = (await readdir(path.join(docsDir, "outputs", "pdf"))).filter((name) => name.toLocaleLowerCase().endsWith(".pdf"));
  actualPdfNames.forEach((name) => invariant(expectedPdfNames.has(name), `Unexpected deployed PDF for a removed or unknown language: docs/outputs/pdf/${name}`));
  invariant(actualPdfNames.length === expectedPdfNames.size, "The deployed PDF inventory does not match langs.json");

  const docsEntries = await readdir(docsDir, { withFileTypes: true });
  for (const entry of docsEntries) {
    if (!entry.isDirectory() || !/^[a-z]{2,3}$/.test(entry.name) || codes.includes(entry.name)) {
      continue;
    }
    const staleIndex = path.join(docsDir, entry.name, "index.html");
    if (await exists(staleIndex)) {
      const source = await readFile(staleIndex, "utf8");
      invariant(!source.includes("Generated by scripts/generate-site.mjs"), `Remove stale generated language page: docs/${entry.name}/index.html`);
    }
  }
  const requiredArtifacts = [
    "CNAME",
    ".nojekyll",
    "cv.json",
    "stacks.json",
    "res/prompts/job_analysis_prompt.txt",
    "res/prompts/fit_summary_prompt.txt",
    "res/prompts/job_application_email_prompt.txt",
    "res/config/models.json",
    "outputs/pdf/cv.pdf",
    "outputs/apk/app-debug.apk"
  ];
  for (const artifact of requiredArtifacts) {
    invariant(await exists(path.join(docsDir, artifact)), `Required deployed artifact is missing: docs/${artifact}`);
  }

  for (const code of codes) {
    const suffix = code === "en" ? "" : `_${code}`;
    const pagePath = code === "en" ? path.join(docsDir, "index.html") : path.join(docsDir, code, "index.html");
    const cv = JSON.parse(await readFile(path.join(docsDir, `cv${suffix}.json`), "utf8"));
    const html = await readFile(pagePath, "utf8");
    const relative = path.relative(root, pagePath);
    invariant(/^<!doctype html>/i.test(html), `${relative} is missing a standards-mode doctype`);
    invariant(html.includes(`<html lang="${code}">`), `${relative} has the wrong document language`);
    invariant(html.includes(`data-page-lang="${code}"`), `${relative} has the wrong runtime language`);
    invariant(html.includes(escapeHtml(cv.name)), `${relative} does not pre-render the CV name`);
    invariant(html.includes(escapeHtml(cv.summary)), `${relative} does not pre-render the summary`);
    invariant((html.match(/class="experience-item"/g) || []).length === cv.experience.length, `${relative} has the wrong experience count`);
    invariant(!html.includes("fetch("), `${relative} must not fetch page content at runtime`);
    invariant(!html.includes("{{"), `${relative} contains an unresolved template placeholder`);
    invariant(html.includes(`rel="canonical" href="https://cv.lutfitek.in${code === "en" ? "/" : `/${code}/`}"`), `${relative} has the wrong canonical URL`);
    for (const alternate of [...codes, "x-default"]) {
      invariant(html.includes(`hreflang="${alternate}"`), `${relative} is missing hreflang ${alternate}`);
    }
    const expectedPdf = `${code === "en" ? "" : "../"}outputs/pdf/cv${suffix}.pdf`;
    invariant(html.includes(`data-pdf-path="${expectedPdf}"`), `${relative} has the wrong PDF mapping`);
    for (const reference of localReferences(html)) {
      await verifyReference(pagePath, reference);
    }
    console.log(`Verified rendered content and routes in ${relative}`);
  }

  const rootHtml = await readFile(path.join(docsDir, "index.html"), "utf8");
  const germanHtml = await readFile(path.join(docsDir, "de", "index.html"), "utf8");
  invariant(rootHtml.includes("window.Android.onPdfReady"), "Root page no longer preserves the Android PDF bridge contract");
  invariant(rootHtml.includes('key === "pdf"'), "Root page no longer recognizes the legacy ?pdf query");
  invariant(rootHtml.includes('key === "lang"'), "Root page no longer recognizes the legacy ?lang query");
  invariant(rootHtml.includes("!requestedLanguage && !pdfMode"), "Bare ?pdf must remain English instead of using browser-language detection");
  invariant(executeRoutingScript(rootHtml, { browserLanguage: "de-DE", android: true }) === null, "Android bare-root loads must not auto-redirect by device language");
  invariant(executeRoutingScript(rootHtml, { browserLanguage: "de-DE" }) === "de/?lang=de", "Browser language detection must route German users to /de/");
  invariant(executeRoutingScript(rootHtml, { search: "?pdf", browserLanguage: "de-DE", android: true }) === null, "Android ?pdf must stay on the English root page for bridge handling");
  invariant(executeRoutingScript(rootHtml, { search: "?pdf", browserLanguage: "de-DE" }) === "outputs/pdf/cv.pdf", "Browser ?pdf must open the English PDF");
  invariant(executeRoutingScript(rootHtml, { search: "?pdf&lang=de" }) === "de/?pdf&lang=de", "Legacy localized PDF queries must preserve parameters while routing to /de/");
  invariant(executeRoutingScript(germanHtml, { search: "?pdf&lang=de" }) === "../outputs/pdf/cv_de.pdf", "German ?pdf must open the German PDF");
  console.log("Static site smoke tests passed");
}

main().catch((error) => {
  console.error(`Static site test failed: ${error.message}`);
  process.exitCode = 1;
});
