name: Android CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/**'

  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    # 1. Grant write permissions for the job
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        # Removed the redundant fallback step as this action is reliable

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Prepare docs folder
        run: |
          mkdir -p docs/outputs/apk
          cp app/build/outputs/apk/debug/*.apk docs/outputs/apk/

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: docs/outputs/apk/*.apk

      - name: Commit APK to main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "$GIT_COMMITTER_NAME"
          git config user.email "$GIT_COMMITTER_EMAIL"
          git add docs/outputs/apk/
          # Check if there are changes to commit before proceeding
          if git diff --staged --quiet; then
            echo "No APK changes to commit."
          else
            # 2. Add [skip ci] to the commit message to prevent a workflow loop
            git commit -m "CI: add built APK [skip ci]"
            git push
          fi
