name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: "12.0"
          accept-android-sdk-licenses: true
          packages: |
            platform-tools
            "platforms;android-34"
            "build-tools;34.0.0"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Prepare docs folder
        run: |
          mkdir -p docs/outputs/apk
          cp app/build/outputs/apk/debug/*.apk docs/outputs/apk/ || true

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: docs/outputs/apk/*.apk

      - name: Commit APK to main (pushes docs/outputs/apk)
        if: github.ref == 'refs/heads/main'
        env:
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "$GIT_COMMITTER_NAME"
          git config user.email "$GIT_COMMITTER_EMAIL"
          git add docs/outputs/apk/*.apk || true
          git commit -m "CI: add built APK" || echo "No APK changes to commit"
          git push origin HEAD:main || echo "Push failed"
