name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 36
          ndk: false
          cmake: false

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Move APK to docs folder
        run: |
          mkdir -p docs/outputs/apk
          cp app/build/outputs/apk/debug/*.apk docs/outputs/apk/

      - name: Upload debug APK (optional)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: docs/outputs/apk/*.apk
